### ISSUE TITLE
configuration flow could not be loaded

### ISSUE THREAD

**Issue by ChristophCaina** [a529987659852/openwbmqtt#11]
When I want to install the OpenWBmqtt Integration, I am getting the following error: "the configuration flow could not be loaded"

![Grafik](https://user-images.githubusercontent.com/26391061/136337073-c5d5f58e-5805-47b6-a920-2912ea7ed03c.png)

I am using the following Setup and versions:

Core: core-2021.10.0
Supervisor: supervisor-2021.09.6
Host: HomeAssistant OS 6.4

installed on a Virtual machine running on a Proxmox server.

Additional information from the Logs:
![Grafik](https://user-images.githubusercontent.com/26391061/136338003-ac1d0360-effc-4080-a783-cfcedc8b9c85.png)
![Grafik](https://user-images.githubusercontent.com/26391061/136338169-4df64ee3-d3f4-4ed5-939a-117cc9b97fa7.png)
```
Logger: aiohttp.server
Source: setup.py:374
First occurred: 09:13:51 (2 occurrences)
Last logged: 09:14:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 151, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 169, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 706, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 374, in async_process_deps_reqs
    raise HomeAssistantError("Could not set up all dependencies.")
homeassistant.exceptions.HomeAssistantError: Could not set up all dependencies.
```

Right now, openWB is not yet installed and available - but I don't think that this should be an issue related to the error above...
I would expect to get the configuration page where I need to set the IP Address of the OpenWB, etc. right?

If not, this should maybe explained a bit more detailed in the Readme documentation :)

**Comment by snoerenberg** [comment]
Hi,

finally install MQTT integration on Homeassistant and enter IP/hostname of OpenWB as MQTT broker. Username/password blank.

I think I will extend it to have some more global properties.
Like: /global/WHouseConsumption, /evu/W, ...

**Comment by snoerenberg** [comment]
I found some fork already adding it.
https://github.com/kaepse/openwbmqtt
another one which added battery.

BTW: thanks a lot for your work!

**Comment by slankes** [comment]
Hi @ChristophCaina - as your issue seems to be resolved - would you mind closing this issue? Thank you.
